# Generated by Django 5.2.3 on 2025-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_listings_comments_bids_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("furniture", "Furniture"),
                    ("books", "Books"),
                    ("kitchen", "Kitchen"),
                    ("sports", "Sports & Outdoors"),
                    ("toys", "Toys & Games"),
                    ("beauty", "Beauty & Health"),
                ],
                max_length=100,
            ),
        ),
    ]
