# Generated by Django 5.2.3 on 2025-09-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_category_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
